import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';
import 'config/firebase_options.dart'; // Generated by FlutterFire CLI
import 'services/auth_service.dart';
import 'models/user_model.dart';
import 'screens/login_screen.dart';
import 'screens/onboarding_screen.dart';
import 'screens/home_screen.dart';
import 'screens/creator_public_page.dart';
import 'screens/subscription_success_screen.dart';

class PendingNavigation {
  static String? returnTo;
  static String? checkoutCreatorUid;
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    MultiProvider(
      providers: [
        Provider<AuthService>(create: (_) => AuthService()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'closr',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.light,
        ),
        fontFamily: 'Roboto',
      ),
      onGenerateRoute: (settings) {
        final uri = Uri.parse(settings.name ?? '/');

        if (uri.pathSegments.isEmpty) {
          return MaterialPageRoute(builder: (_) => const AuthWrapper());
        }

        final path = uri.pathSegments.first;
        const reservedRoutes = {'login', 'home', 'profile', 'onboarding'};

        if (path == 'subscription-success') {
          final creatorUsername = uri.queryParameters['creator'] ?? '';
          return MaterialPageRoute(
            builder: (_) => SubscriptionSuccessScreen(creatorUsername: creatorUsername),
          );
        }

        if (reservedRoutes.contains(path)) {
          return MaterialPageRoute(builder: (_) => const AuthWrapper());
        }

        return MaterialPageRoute(
          builder: (_) => CreatorPublicPage(username: path),
          settings: settings,
        );
      },
      home: const AuthWrapper(),
      debugShowCheckedModeBanner: false,
    );
  }
}

/// AuthWrapper handles the routing logic based on authentication state
class AuthWrapper extends StatefulWidget {
  const AuthWrapper({Key? key}) : super(key: key);

  @override
  State<AuthWrapper> createState() => _AuthWrapperState();
}

class _AuthWrapperState extends State<AuthWrapper> {
  late final AuthService _authService;

  @override
  void initState() {
    super.initState();
    _authService = context.read<AuthService>();
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: _authService.authStateChanges,
      builder: (context, snapshot) {
        // Loading state
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }

        // Not authenticated - show login
        if (!snapshot.hasData) {
          return const LoginScreen();
        }

        final firebaseUser = snapshot.data!;

        // Authenticated - check if profile exists
        return FutureBuilder<AppUser?>(
          future: _authService.getUserProfile(firebaseUser.uid),
          builder: (context, profileSnapshot) {
            if (profileSnapshot.connectionState == ConnectionState.waiting) {
              return const Scaffold(
                body: Center(
                  child: CircularProgressIndicator(),
                ),
              );
            }

            // No profile yet - show onboarding
            if (!profileSnapshot.hasData || profileSnapshot.data == null) {
              return OnboardingScreen(
                uid: firebaseUser.uid,
                email: firebaseUser.email ?? 'unknown@example.com',
                displayName: firebaseUser.displayName ?? 'User',
                photoUrl: firebaseUser.photoURL,
              );
            }

            // Profile exists — redirect if a post-auth navigation is pending
            final pending = PendingNavigation.returnTo;
            if (pending != null) {
              PendingNavigation.returnTo = null;
              WidgetsBinding.instance.addPostFrameCallback((_) {
                Navigator.of(context).pushNamedAndRemoveUntil(pending, (_) => false);
              });
            }
            return HomeScreen(user: profileSnapshot.data!);
          },
        );
      },
    );
  }
}
